apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lightnvr

resources:
  - namespace.yaml
  - pvc.yaml
  - go2rtc-configmap.yaml
  - wireguard-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

