# WireGuard configuration secret
# Replace the wg0.conf content with your actual WireGuard config
#
# To generate keys:
#   wg genkey | tee privatekey | wg pubkey > publickey
#
# To update this secret:
#   kubectl -n lightnvr create secret generic wireguard-config \
#     --from-file=wg0.conf=./wg0.conf \
#     --dry-run=client -o yaml | kubectl apply -f -
#
apiVersion: v1
kind: Secret
metadata:
  name: wireguard-config
  namespace: lightnvr
type: Opaque
stringData:
  wg0.conf: |
    [Interface]
    PrivateKey = kA60csLZCDwt8QSkYpS3zZ7G3QxstnDgCSNuDnxwMn0=
    Address = 10.6.0.4/32

    [Peer]
    # ASUS router WireGuard server
    PublicKey = FwTW+9iDPR5VRxVj+7l8uuqMvB45ugHBIa1iw5Uxt2Y=
    Endpoint = matteius.asuscomm.com:51820
    # Only route home LAN and WG subnet â€” NOT 0.0.0.0/0
    # (0.0.0.0/0 would hijack all pod traffic and break ingress)
    AllowedIPs = 192.168.50.0/24, 10.6.0.0/24
    PersistentKeepalive = 25

