# go2rtc configuration file
api:
  listen: :1984
  origin: "*"

rtsp:
  listen: :8554

webrtc:
  listen: :8555
  ice_servers:
    - urls: [stun:stun.l.google.com:19302]
  candidates:
    - "*:8555"
    - stun:stun.l.google.com:19302

log:
  level: info

streams:
  # Streams will be added dynamically by LightNVR
  Full:
    - rtsp://thingino:thingino@192.168.82.156:554/ch1#transport=tcp#timeout=30
    - ffmpeg:Full#video=copy#audio=aac
